/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.FDA;

import Business.Enterprise.Enterprise;
import Business.FDA.FDA;
import Business.ManifacturingWarehouse.ManufacturingWarehouse;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.FDAApprovalRequest;
import Business.WorkQueue.WorkRequest;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author gauthamrajsimhapulipati
 */
public class FDAAdminWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form FDAAdminWorkAreaJPanel
     */
    
    private JPanel userProcessContainer;
    private UserAccount account;
    private ArrayList<Enterprise> warehouseEnterprises;
    private FDA fda;
    
    public FDAAdminWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, ArrayList<Enterprise> warehouseEnterprises, FDA fda) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.warehouseEnterprises = warehouseEnterprises;
        this.fda = fda;
        populateTable();
    }
    
    private void populateTable(){
        DefaultTableModel model = (DefaultTableModel)tblRequest.getModel();
        model.setRowCount(0);
        
        for(Enterprise e:warehouseEnterprises){
            for(ManufacturingWarehouse mw:e.getManufacturingWarehouseDirectory().getWarehousedirectory()){
                ArrayList<WorkRequest> wr = mw.getWorkQueue().getWorkRequestList3();
                for(int i=wr.size()-1; i>=0;i--){
                    FDAApprovalRequest lt = (FDAApprovalRequest)wr.get(i);
                    Object[] row = new Object[4];
                    row[0] = lt;
                    row[1] = lt.getProduct();
                    row[2] = lt.getMw();
                    row[3] = lt.getStatus();
                    model.addRow(row);
                }
            }
        }
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblRequest = new javax.swing.JTable();
        btnApprove = new javax.swing.JButton();
        btnDeny = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnRefresh = new javax.swing.JButton();

        setBackground(new java.awt.Color(234, 248, 218));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblRequest.setBackground(new java.awt.Color(187, 222, 249));
        tblRequest.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 204, 255), 3, true));
        tblRequest.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Message", "Product", "Warehouse", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblRequest);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 228, 536, 175));

        btnApprove.setBackground(new java.awt.Color(153, 255, 153));
        btnApprove.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        btnApprove.setText("Approve");
        btnApprove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApproveActionPerformed(evt);
            }
        });
        add(btnApprove, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 430, 100, 30));

        btnDeny.setBackground(new java.awt.Color(255, 102, 102));
        btnDeny.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        btnDeny.setText("Deny");
        btnDeny.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDenyActionPerformed(evt);
            }
        });
        add(btnDeny, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 430, 110, 30));

        jPanel1.setBackground(new java.awt.Color(187, 222, 249));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 204, 255), 3, true));

        jLabel1.setFont(new java.awt.Font("Devanagari MT", 1, 36)); // NOI18N
        jLabel1.setText("FDA Admin Process");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(283, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(279, 279, 279))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jLabel1)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 911, -1));

        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });
        add(btnRefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 240, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnApproveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApproveActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblRequest.getSelectedRow();
        if (selectedRow < 0){
            JOptionPane.showMessageDialog(this, "Please select a row to accept");
            return;
        }
        FDAApprovalRequest request = (FDAApprovalRequest) tblRequest.getValueAt(selectedRow, 0);
        if(request.getStatus().equals("Waiting")){
            request.setStatus("Approved");
            request.getProduct().setStatus("Approved");
        }
        else{
            JOptionPane.showMessageDialog(this, "Previously accepted or denied");
            return;
        }
        
        
    }//GEN-LAST:event_btnApproveActionPerformed

    private void btnDenyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDenyActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblRequest.getSelectedRow();
        if (selectedRow < 0){
            JOptionPane.showMessageDialog(this, "Please select a row to accept");
            return;
        }
        FDAApprovalRequest request = (FDAApprovalRequest) tblRequest.getValueAt(selectedRow, 0);
        if(request.getStatus().equals("Waiting")){
            request.setStatus("Denied");
            request.getProduct().setStatus("Denied");
        }
        else{
            JOptionPane.showMessageDialog(this, "Previously approved or denied");
            return;
        }
    }//GEN-LAST:event_btnDenyActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        populateTable();
    }//GEN-LAST:event_btnRefreshActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApprove;
    private javax.swing.JButton btnAssign;
    private javax.swing.JButton btnAssign1;
    private javax.swing.JButton btnDeny;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblRequest;
    // End of variables declaration//GEN-END:variables
}
