/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.HospitalEnterpriseAdmin;

import Business.Employee.Employee;
import Business.Enterprise.Enterprise;
import Business.Hospital.Hospital;
import Business.Role.TechnicianRole;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author aksha
 */
public class CreateLabTechnicianJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateLabTechnicianJPanel
     */
    private JPanel userProcessContainer;
    private Enterprise enterprise;
    
    public CreateLabTechnicianJPanel(JPanel userProcessContainer, Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        populateJComboBox();
    }
    
    private void populateJComboBox(){
        hospitalJComboBox.removeAllItems();
        int i=0;
        for(Hospital hos :enterprise.getHospitalDirectory().getHospitals()){
            if(i==0){
                populateTable(hos);
                i++;
                System.out.println(hos.getHospitalName());
            }
            hospitalJComboBox.addItem(hos);
        }
    }
    
    private void populateTable(Hospital hospital){
        DefaultTableModel model = (DefaultTableModel)tblTechnicians.getModel();
        model.setRowCount(0);
        //String dm = "Business.Role.LabAdminRole";
        String dm = "Technician";
        
        for(UserAccount us: hospital.getUserAccountDirectory().getUserAccountList()){
            if(us.getRole().toString().equals(dm)){
                Object[] row = new Object[2];
                row[0] = us;
                row[1] = us.getEmployee().getName();
                model.addRow(row);
            }
            
        }
    }

   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTechnicians = new javax.swing.JTable();
        btnSubmit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtTechnicianName = new javax.swing.JTextField();
        txtTechnicianUsername = new javax.swing.JTextField();
        txtPassword = new javax.swing.JTextField();
        hospitalJComboBox = new javax.swing.JComboBox();
        btnDelete = new javax.swing.JButton();
        btnModify = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();

        setBackground(new java.awt.Color(155, 231, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel2.setText("Technician Name:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 392, 170, 32));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel3.setText("Technician Username:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 442, 170, 32));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel4.setText("Password:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 492, 170, 32));

        tblTechnicians.setBackground(new java.awt.Color(204, 204, 255));
        tblTechnicians.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Technician Username", "Technicain Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblTechnicians);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 156, 653, 156));

        btnSubmit.setBackground(new java.awt.Color(204, 153, 255));
        btnSubmit.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        btnSubmit.setText("Submit");
        btnSubmit.setPreferredSize(new java.awt.Dimension(81, 27));
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        add(btnSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 550, 100, 40));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel1.setText("Hospital Name:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 342, 170, 32));

        txtTechnicianName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTechnicianNameActionPerformed(evt);
            }
        });
        add(txtTechnicianName, new org.netbeans.lib.awtextra.AbsoluteConstraints(401, 398, 140, 21));
        add(txtTechnicianUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(401, 448, 140, 21));
        add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(401, 498, 140, 21));

        hospitalJComboBox.setBackground(new java.awt.Color(180, 223, 229));
        hospitalJComboBox.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        hospitalJComboBox.setForeground(new java.awt.Color(48, 60, 108));
        hospitalJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        hospitalJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hospitalJComboBoxActionPerformed(evt);
            }
        });
        add(hospitalJComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(401, 347, 140, -1));

        btnDelete.setBackground(new java.awt.Color(204, 153, 255));
        btnDelete.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(776, 272, 100, 40));

        btnModify.setBackground(new java.awt.Color(204, 153, 255));
        btnModify.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        btnModify.setText("Modify");
        btnModify.setPreferredSize(new java.awt.Dimension(100, 40));
        btnModify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifyActionPerformed(evt);
            }
        });
        add(btnModify, new org.netbeans.lib.awtextra.AbsoluteConstraints(776, 156, -1, -1));

        jPanel1.setBackground(new java.awt.Color(121, 83, 210));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(69, 39, 160), 10, true));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setBackground(new java.awt.Color(69, 39, 160));
        jLabel5.setFont(new java.awt.Font("Devanagari MT", 1, 36)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Create Lab Technician");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 48, 385, -1));

        btnBack.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel1.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 21, 90, 32));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 130));
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
        Hospital hospital = (Hospital) hospitalJComboBox.getSelectedItem();
        
        String username = txtTechnicianUsername.getText();
        String password = txtPassword.getText();
        String name = txtTechnicianName.getText();
        
        if(username.isEmpty() || name.isEmpty() || password.isEmpty() ){
        
            JOptionPane.showMessageDialog(this, "All Fields are Mandatory");
            return;
        }
        boolean isValid ; 
        
        isValid = name.matches("^[a-zA-Z]+$");
        if(!isValid) {
            JOptionPane.showMessageDialog(null, "Name must contains only alphabets");
            txtTechnicianName.setText("");
            return;
        }
        if(hospital.getUserAccountDirectory().checkIfUsernameIsUnique(username) == false){
            JOptionPane.showMessageDialog(this, "user name taken, try another one");
            txtTechnicianUsername.setText("");
            txtPassword.setText("");
            return;
        }
        
        isValid = username.matches("^[a-zA-Z0-9]+$");
        
        if(!isValid) {
            JOptionPane.showMessageDialog(null, "Username must be Alphanumeric");
            txtTechnicianUsername.setText("");
            return;
        }
        
        isValid = password.matches("^[a-zA-Z0-9]+$$");
        
        if(!isValid) {
            JOptionPane.showMessageDialog(null, "Password must be Alphanumeric");
            txtPassword.setText("");
            return;
        }

        if(password.length()<6){
            JOptionPane.showMessageDialog(this, "Password too weak, choose a password with a minimum length of 6");
            txtPassword.setText("");
            return;
        }
        
        Employee employee = hospital.getEmployeeDirectory().createEmployee(name);
        UserAccount ua = hospital.getUserAccountDirectory().createUserAccount(username, password, employee, new TechnicianRole());
        //System.out.println(hospital.getUserAccountDirectory().getUserAccountList().size()+" ---- aaa");
        populateTable(hospital);
        
        txtTechnicianUsername.setText("");
        txtPassword.setText("");
        txtTechnicianName.setText("");
        btnDelete.setEnabled(true);
        btnModify.setEnabled(true);
        
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void txtTechnicianNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTechnicianNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTechnicianNameActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        HospitalEnterpriseAdminJPanel hentadjp = (HospitalEnterpriseAdminJPanel) component;
        //sysAdminwjp.populateTree();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void hospitalJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hospitalJComboBoxActionPerformed
        // TODO add your handling code here:
        Hospital hospital = (Hospital) hospitalJComboBox.getSelectedItem();
        if(hospital!=null){
            populateTable(hospital);
        }
    }//GEN-LAST:event_hospitalJComboBoxActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        Hospital hosp = (Hospital) hospitalJComboBox.getSelectedItem();

        int selectedRow = tblTechnicians.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please Select a row from table first", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        DefaultTableModel model = (DefaultTableModel) tblTechnicians.getModel();

        UserAccount us = (UserAccount) model.getValueAt(selectedRow, 0);

        hosp.getEmployeeDirectory().deleteEmployee(us.getEmployee());
        hosp.getUserAccountDirectory().removeUser(us);
        populateTable(hosp);
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnModifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifyActionPerformed
        Hospital hosp = (Hospital) hospitalJComboBox.getSelectedItem();
        int selectedRowIndex = tblTechnicians.getSelectedRow();

        if(selectedRowIndex<0){
            JOptionPane.showMessageDialog(this, "Please select a row to Modify");
            return;
        }
        DefaultTableModel model = (DefaultTableModel) tblTechnicians.getModel();
        UserAccount us = (UserAccount) model.getValueAt(selectedRowIndex, 0);
        txtTechnicianUsername.setText(us.getUsername());
        txtPassword.setText(us.getPassword());
        txtTechnicianName.setText(us.getEmployee().getName());
        hosp.getUserAccountDirectory().removeUser(us);
        btnDelete.setEnabled(false);
        btnModify.setEnabled(false);
    }//GEN-LAST:event_btnModifyActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnModify;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JComboBox hospitalJComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblTechnicians;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtTechnicianName;
    private javax.swing.JTextField txtTechnicianUsername;
    // End of variables declaration//GEN-END:variables
}
