/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Store;

import Business.Distribution.Distribution;
import Business.Enterprise.Enterprise;
import Business.ManifacturingWarehouse.ManufacturingWarehouse;
import Business.Order.Order;
import Business.Products.Product;
import Business.RetailStore.RetailStore;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.StoreAdminOrderWorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author gauthamrajsimhapulipati
 */
public class PlaceOrderRetaliJPanel extends javax.swing.JPanel {

    /**
     * Creates new form PlaceOrderRetaliJPanel
     */
    private JPanel userProcessContainer;
    private UserAccount useraccount;
    private ArrayList<Enterprise> dlist;
    private RetailStore retailStore;
    
    public PlaceOrderRetaliJPanel(JPanel userProcessContainer,UserAccount useraccount, ArrayList<Enterprise> dlist, RetailStore retailStore) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.useraccount = useraccount;
        this.dlist = dlist;
        this.retailStore = retailStore;
        txtQuantity.setText("1");
        txtTotal.setText("0");
        DefaultTableModel model1 = (DefaultTableModel) tblOrder.getModel();
        model1.setRowCount(0);
        populateJComboBox1();
        
    }
    
    private void populateJComboBox1(){
        enterpriseJComboBox.removeAllItems();
        int i=0;
        for(Enterprise enterprise: dlist){
            if(i==0){
                populateJComboBox(enterprise.getDistributionDirectory().getDistributions());
                i++;
            }
            enterpriseJComboBox.addItem(enterprise);
        }
    }
    
    private void populateJComboBox(ArrayList<Distribution> ds){
        distributionJComboBox.removeAllItems();
        int i=0;
        for(Distribution d :ds){
            if(i==0){
                populateTableProducts(d);
                i++;
                System.out.println(d.getDistributionName());
            }
            distributionJComboBox.addItem(d);
        }
    }
    
    private void populateTableProducts(Distribution d){
        DefaultTableModel model = (DefaultTableModel)tblProducts.getModel();
        model.setRowCount(0);
        //String dm = "Business.Role.LabAdminRole";
        
        for(Product product:d.getProductDirectory().getProducts()){
            Object[] row = new Object[3];
            row[0] = product;
            row[1] = product.getQuantity();
            row[2] = product.getPrice();
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAddToCart = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblOrder = new javax.swing.JTable();
        txtMessage = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProducts = new javax.swing.JTable();
        btnPlaceOrder = new javax.swing.JButton();
        txtTotal = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtQuantity = new javax.swing.JTextField();
        distributionJComboBox = new javax.swing.JComboBox();
        enterpriseJComboBox = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnBack = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(247, 237, 226));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAddToCart.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        btnAddToCart.setText("Add to cart");
        btnAddToCart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddToCartActionPerformed(evt);
            }
        });
        add(btnAddToCart, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 430, -1, 41));

        jLabel5.setFont(new java.awt.Font("Devanagari MT", 1, 14)); // NOI18N
        jLabel5.setText("Message :");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 490, 78, -1));

        tblOrder.setBackground(new java.awt.Color(255, 153, 153));
        tblOrder.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Test Kit", "Selected Quantity", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblOrder);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 490, 502, 153));
        add(txtMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 510, 183, 69));

        tblProducts.setBackground(new java.awt.Color(255, 153, 153));
        tblProducts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Test Kit", "Available Quantity", "Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Integer.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblProducts);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 226, 502, 187));

        btnPlaceOrder.setBackground(new java.awt.Color(239, 35, 60));
        btnPlaceOrder.setFont(new java.awt.Font("Devanagari MT", 1, 14)); // NOI18N
        btnPlaceOrder.setText("Place Order");
        btnPlaceOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlaceOrderActionPerformed(evt);
            }
        });
        add(btnPlaceOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 700, -1, 40));

        txtTotal.setText("0");
        add(txtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 650, 77, -1));

        jLabel2.setFont(new java.awt.Font("Devanagari MT", 1, 14)); // NOI18N
        jLabel2.setText("Total Price");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 650, -1, -1));

        jLabel1.setFont(new java.awt.Font("Devanagari MT", 1, 14)); // NOI18N
        jLabel1.setText("Quantity:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 230, 70, -1));

        txtQuantity.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        txtQuantity.setText("1");
        txtQuantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQuantityActionPerformed(evt);
            }
        });
        add(txtQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 230, 114, -1));

        distributionJComboBox.setBackground(new java.awt.Color(180, 223, 229));
        distributionJComboBox.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        distributionJComboBox.setForeground(new java.awt.Color(48, 60, 108));
        distributionJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        distributionJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                distributionJComboBoxActionPerformed(evt);
            }
        });
        add(distributionJComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 162, 193, -1));

        enterpriseJComboBox.setBackground(new java.awt.Color(180, 223, 229));
        enterpriseJComboBox.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        enterpriseJComboBox.setForeground(new java.awt.Color(48, 60, 108));
        enterpriseJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        enterpriseJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterpriseJComboBoxActionPerformed(evt);
            }
        });
        add(enterpriseJComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(583, 162, 189, -1));

        jLabel4.setFont(new java.awt.Font("Devanagari MT", 1, 14)); // NOI18N
        jLabel4.setText("Select Distribution");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 165, -1, -1));

        jLabel6.setFont(new java.awt.Font("Devanagari MT", 1, 14)); // NOI18N
        jLabel6.setText("Select Enterprise");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(433, 165, -1, -1));

        jPanel2.setBackground(new java.awt.Color(239, 35, 60));

        btnBack.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Devanagari MT", 1, 36)); // NOI18N
        jLabel3.setText("Retail Store Place Order");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBack)
                .addGap(88, 88, 88)
                .addComponent(jLabel3)
                .addContainerGap(174, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnBack))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel3)))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddToCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddToCartActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = tblProducts.getSelectedRow();
        if(selectedRowIndex<0){
            JOptionPane.showMessageDialog(this, "Please select a row to add");
            return;
        }
        DefaultTableModel model = (DefaultTableModel) tblProducts.getModel();
        Product product = (Product) model.getValueAt(selectedRowIndex, 0);
        DefaultTableModel model1 = (DefaultTableModel) tblOrder.getModel();

        if(product.getQuantity()< Integer.parseInt(txtQuantity.getText())){
            JOptionPane.showMessageDialog(this, "Product unavailable");
            return;
        }

        Object[] row = new Object[3];
        row[0] = product;
        row[1] = Integer.parseInt(txtQuantity.getText());
        row[2] = Integer.parseInt(txtQuantity.getText())*product.getPrice();
        model1.addRow(row);

        txtQuantity.setText("1");
        double total = Double.parseDouble(txtTotal.getText()) + Integer.parseInt(txtQuantity.getText())*product.getPrice();
        txtTotal.setText(String.valueOf(total));
    }//GEN-LAST:event_btnAddToCartActionPerformed

    private void btnPlaceOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlaceOrderActionPerformed
        // TODO add your handling code here:
        String message = txtMessage.getText();
        Distribution distribution = (Distribution) distributionJComboBox.getSelectedItem();
        Order order = new Order();

        DefaultTableModel model = (DefaultTableModel) tblOrder.getModel();
        int noOfRows = model.getRowCount();
        for(int i=0;i<noOfRows;i++){
            Product product = (Product) model.getValueAt(i, 0);
            Integer quant = (Integer) model.getValueAt(i, 1);
            System.out.println(product.getProductName());
            order.addItem(product, quant);
        }
        order.setPrice(Double.parseDouble(txtTotal.getText()));

        StoreAdminOrderWorkRequest request = new StoreAdminOrderWorkRequest();
        request.setMessage(message);
        request.setDistribution(distribution);
        request.setSender(useraccount);
        request.setStatus("Retail Order placed");
        request.setOrders(order);
        request.setDistribution(distribution);

        distribution.addOrder(order);

        if(distribution ==null){
            System.out.println("nonono");
        }
        else{
            distribution.getWorkQueue().getWorkRequestList2().add(request);
            useraccount.getWorkQueue().getWorkRequestList2().add(request);
        }
        model.setRowCount(0);
    }//GEN-LAST:event_btnPlaceOrderActionPerformed

    private void distributionJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_distributionJComboBoxActionPerformed
        // TODO add your handling code here:
        Distribution distribution = (Distribution) distributionJComboBox.getSelectedItem();
        if(distribution!=null){
            populateTableProducts(distribution);
        }
    }//GEN-LAST:event_distributionJComboBoxActionPerformed

    private void enterpriseJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterpriseJComboBoxActionPerformed
        // TODO add your handling code here:
        Enterprise enterprise = (Enterprise) enterpriseJComboBox.getSelectedItem();
        if(enterprise!=null){
            populateJComboBox(enterprise.getDistributionDirectory().getDistributions());
        }
    }//GEN-LAST:event_enterpriseJComboBoxActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        StoreAdminJPanel hentadjp = (StoreAdminJPanel) component;
        //sysAdminwjp.populateTree();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void txtQuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQuantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQuantityActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddToCart;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnPlaceOrder;
    private javax.swing.JComboBox distributionJComboBox;
    private javax.swing.JComboBox enterpriseJComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblOrder;
    private javax.swing.JTable tblProducts;
    private javax.swing.JTextField txtMessage;
    private javax.swing.JTextField txtQuantity;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
