/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.ConsultDoctor;

import Business.Hospital.Hospital;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.ConsultDoctorRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author gauthamrajsimhapulipati
 */
public class ConsultDoctorJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ConsultDoctorJPanel
     */
    
    private JPanel userProcessContainer;
    private UserAccount account;
    private Hospital hospital;
    
    public ConsultDoctorJPanel(JPanel userProcessContainer, UserAccount account, Hospital hospital) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.hospital = hospital;
        populateTable();
    }
    
    private void populateSymptomsTable(ArrayList<String> symptoms){
        DefaultTableModel model = (DefaultTableModel)tblSymptoms.getModel();
        model.setRowCount(0);
        
        for(String str:symptoms){
            Object[] row = new Object[1];
            row[0] = str;
            model.addRow(row);
        }
    }
    
    private void populateTable(){
        DefaultTableModel model = (DefaultTableModel)tblRequest.getModel();
        model.setRowCount(0);
        //System.out.println(hospital.get);
        ArrayList<WorkRequest> wr = hospital.getWorkQueue().getWorkRequestList3();
        for(int i=wr.size()-1; i>=0;i--){
            ConsultDoctorRequest req = (ConsultDoctorRequest)wr.get(i);
            
            
//            if(!req.getStatus().equals("Sent to Doctor")){
//                continue;
//            }
            Object[] row = new Object[3];
            row[0] = req;
            row[1] = req.getCustomer().getEmployee().getName();
            row[2] = req.getStatus();
           
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblRequest = new javax.swing.JTable();
        viewSymptoma = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblSymptoms = new javax.swing.JTable();
        btnSuggestTest = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(216, 243, 220));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblRequest.setBackground(new java.awt.Color(204, 255, 204));
        tblRequest.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Message", "Customer Name", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblRequest);
        if (tblRequest.getColumnModel().getColumnCount() > 0) {
            tblRequest.getColumnModel().getColumn(1).setHeaderValue("Customer Name");
            tblRequest.getColumnModel().getColumn(2).setHeaderValue("Status");
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 156, 720, 96));

        viewSymptoma.setBackground(new java.awt.Color(116, 198, 157));
        viewSymptoma.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        viewSymptoma.setText("View Symptoms");
        viewSymptoma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewSymptomaActionPerformed(evt);
            }
        });
        add(viewSymptoma, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 286, -1, 60));

        tblSymptoms.setBackground(new java.awt.Color(204, 255, 204));
        tblSymptoms.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Symptoms"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblSymptoms);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 374, 720, 96));

        btnSuggestTest.setBackground(new java.awt.Color(116, 198, 157));
        btnSuggestTest.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        btnSuggestTest.setText("Suggest Test");
        btnSuggestTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuggestTestActionPerformed(evt);
            }
        });
        add(btnSuggestTest, new org.netbeans.lib.awtextra.AbsoluteConstraints(628, 286, 151, 60));

        jPanel1.setBackground(new java.awt.Color(116, 198, 157));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(239, 239, 239), 4));

        jLabel1.setFont(new java.awt.Font("Georgia", 1, 36)); // NOI18N
        jLabel1.setText("Consulting Doctor");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(242, 242, 242)
                .addComponent(jLabel1)
                .addContainerGap(262, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void viewSymptomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewSymptomaActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = tblRequest.getSelectedRow();
        if(selectedRowIndex<0){
            JOptionPane.showMessageDialog(this, "Please select a row to add");
            return;
        }
        
        DefaultTableModel model = (DefaultTableModel) tblRequest.getModel();
        ConsultDoctorRequest request = (ConsultDoctorRequest) model.getValueAt(selectedRowIndex, 0);
        
        populateSymptomsTable(request.getSymptoms());
    }//GEN-LAST:event_viewSymptomaActionPerformed

    private void btnSuggestTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuggestTestActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblRequest.getSelectedRow();
        
        if (selectedRow < 0){
            JOptionPane.showMessageDialog(this, "Please select a row to suggest test");
            return;
        }
        
        ConsultDoctorRequest request = (ConsultDoctorRequest)tblRequest.getValueAt(selectedRow, 0);
        request.setStatus("Pending Suggestion");
        
        DoctorConsultJPanel doctorConsultJPanel = new DoctorConsultJPanel(userProcessContainer, request);
        userProcessContainer.add("DoctorConsultJPanel", doctorConsultJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
    }//GEN-LAST:event_btnSuggestTestActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSuggestTest;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblRequest;
    private javax.swing.JTable tblSymptoms;
    private javax.swing.JButton viewSymptoma;
    // End of variables declaration//GEN-END:variables
}
