/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package info5100.university.example.ui.Student;

import info5100.university.example.CourseCatalog.Course;
import info5100.university.example.CourseCatalog.CourseCatalog;
import info5100.university.example.CourseSchedule.CourseOffer;
import info5100.university.example.CourseSchedule.Seat;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mrigesh
 */
public class CourseRegisterJPanel extends javax.swing.JPanel {

    CourseCatalog courseCatalog;
    int sum =0;

    /**
     * Creates new form CourseRegisterJPanel
     */
    public CourseRegisterJPanel() {
        initComponents();

        //  populateCourseCatalogTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tableCourseOfferings = new javax.swing.JTable();
        btnSubmit = new javax.swing.JButton();
        btnAddCourse = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableCourseSelected = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCreditTot = new javax.swing.JTextField();

        setBackground(new java.awt.Color(153, 204, 255));

        tableCourseOfferings.setBackground(new java.awt.Color(255, 255, 204));
        tableCourseOfferings.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 51), 1, true));
        tableCourseOfferings.setFont(new java.awt.Font("Comic Sans MS", 1, 10)); // NOI18N
        tableCourseOfferings.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"6100", "Web Design/User Experience", "4", "Vishal Chawla", "40"},
                {"5100", "Application Enginnering & Development", "4", "Karl Bugrara", "200"},
                {"2300", "Program Structure and Algorithms", "4", "Robin Hilyard", "40"},
                {"3232", "ENCP", "1", "Melissa D", null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Course No", "Course Name", "Credits", "Professor", "Seatsl"
            }
        ));
        tableCourseOfferings.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tableCourseOfferings.setGridColor(new java.awt.Color(204, 204, 204));
        jScrollPane2.setViewportView(tableCourseOfferings);

        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        btnAddCourse.setText("Add Course");
        btnAddCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCourseActionPerformed(evt);
            }
        });

        tableCourseSelected.setBackground(new java.awt.Color(255, 255, 204));
        tableCourseSelected.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 51), 1, true));
        tableCourseSelected.setFont(new java.awt.Font("Comic Sans MS", 1, 10)); // NOI18N
        tableCourseSelected.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Course No", "Course Name", "Credits", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tableCourseSelected.setGridColor(new java.awt.Color(204, 204, 204));
        tableCourseSelected.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(tableCourseSelected);

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel1.setText("Register For Course");

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel2.setText("Total Credits");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(57, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnAddCourse)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 641, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(18, 18, 18)
                            .addComponent(txtCreditTot, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSubmit))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 641, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(38, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(269, 269, 269))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addGap(34, 34, 34)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAddCourse)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSubmit)
                    .addComponent(jLabel2)
                    .addComponent(txtCreditTot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(43, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCourseActionPerformed
        int selectedRowIndex = tableCourseOfferings.getSelectedRow();
        if (selectedRowIndex < 0) {
            JOptionPane.showMessageDialog(this, "Please select a Course first!!!");
        }

        int i = 0;
        //   Course course = (Course) tableCourseOfferings.getValueAt(selectedRowIndex, 0);
        Object courseNo = tableCourseOfferings.getValueAt(selectedRowIndex, 0);
        Object courseName = tableCourseOfferings.getValueAt(selectedRowIndex, 1);
        Object Credit = tableCourseOfferings.getValueAt(selectedRowIndex, 2);

        ArrayList<Object> cartDetails = new ArrayList<Object>();
        cartDetails.add(courseNo);
        cartDetails.add(courseName);
        cartDetails.add(Credit);

        populateCartTable(cartDetails);
        
        sum = sum + Integer.parseInt(String.valueOf(tableCourseOfferings.getValueAt(0, 2)));
        
        txtCreditTot.setText(String.valueOf(sum));
       
    }//GEN-LAST:event_btnAddCourseActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        
        if(Integer.parseInt(txtCreditTot.getText()) > 9){
            JOptionPane.showMessageDialog(this, "Maximum Credit Hours are 9");
        }
        
        
    }//GEN-LAST:event_btnSubmitActionPerformed

    public void populateCourseCatalogTable() {

        DefaultTableModel model = (DefaultTableModel) tableCourseOfferings.getModel();
        model.setRowCount(0);
        CourseOffer co = new CourseOffer();

        for (Course c : courseCatalog.getCourseList()) {
            Object row[] = new Object[5];
            row[0] = c.getName();
            row[1] = c.getCOurseNumber();
            row[2] = c.getCredits();
//          row[3] =     // Professor Name
            row[4] = co.getSeatsAvailable();
            model.addRow(row);
        }

    }

    private void populateCartTable(ArrayList<Object> cartDetails) {

        DefaultTableModel model = (DefaultTableModel) tableCourseSelected.getModel();
        //   model.setRowCount(0);
        int i = 0;
        Object row[] = new Object[3];
        row[0] = cartDetails.get(0);
        row[1] = cartDetails.get(1);
        row[2] = cartDetails.get(2);
        model.addRow(row);

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddCourse;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tableCourseOfferings;
    private javax.swing.JTable tableCourseSelected;
    private javax.swing.JTextField txtCreditTot;
    // End of variables declaration//GEN-END:variables
}
