/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Manager;

import Business.Distribution.Distribution;
import Business.Enterprise.Enterprise;
import Business.Products.Product;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.ShippingOrderWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author gauthamrajsimhapulipati
 */


public class ManagerWorkJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManagerWorkJPanel
     */
    
    private JPanel userProcessContainer;
    private UserAccount useraccount;
    private ArrayList<Enterprise> warehouseEnterprises;
    private Distribution distribution;
    
    public ManagerWorkJPanel(JPanel userProcessContainer, UserAccount useraccount, ArrayList<Enterprise> warehouseEnterprises, Distribution distribution) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.useraccount = useraccount;
        this.warehouseEnterprises = warehouseEnterprises;
        this.distribution = distribution;
        
        populateTable();
        
        for(Product product:distribution.getProductDirectory().getProducts()){
            System.out.println(product.getDistribution());
        }
    }
    
    private void populateTable(){
        DefaultTableModel model = (DefaultTableModel) tblWorkRequest.getModel();
        
        model.setRowCount(0);
        
        ArrayList<WorkRequest> wr = useraccount.getWorkQueue().getWorkRequestList();
        
        for (int i=wr.size()-1; i>=0;i--){
            ShippingOrderWorkRequest req = (ShippingOrderWorkRequest)wr.get(i);
            Object[] row = new Object[4];
            row[0] = req;
            row[1] = req.getReceiver();
            row[2] = req.getManufacturingWarehouse();
            row[3] = req.getStatus();
            model.addRow(row);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnShippingOrder = new javax.swing.JButton();
        btnDeliveryMan = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblWorkRequest = new javax.swing.JTable();
        btnRefresh = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 236, 179));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnShippingOrder.setBackground(new java.awt.Color(203, 186, 131));
        btnShippingOrder.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        btnShippingOrder.setText("Place Shipping Order");
        btnShippingOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShippingOrderActionPerformed(evt);
            }
        });
        add(btnShippingOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 426, -1, 60));

        btnDeliveryMan.setBackground(new java.awt.Color(203, 186, 131));
        btnDeliveryMan.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        btnDeliveryMan.setText("Assign Delivery Man");
        btnDeliveryMan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeliveryManActionPerformed(evt);
            }
        });
        add(btnDeliveryMan, new org.netbeans.lib.awtextra.AbsoluteConstraints(442, 426, 191, 60));

        tblWorkRequest.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Message", "Receiver", "Warehouse", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblWorkRequest);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 174, 588, 208));

        btnRefresh.setBackground(new java.awt.Color(203, 186, 131));
        btnRefresh.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });
        add(btnRefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(527, 126, 106, 37));

        jPanel1.setBackground(new java.awt.Color(203, 186, 131));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(239, 239, 239), 4));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("ITF Devanagari", 1, 36)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Manager Process");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, 374, 40));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 698, 100));
    }// </editor-fold>//GEN-END:initComponents

    private void btnShippingOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShippingOrderActionPerformed
        // TODO add your handling code here:
        ManagerOrderJPanel managerOrderJPanel = new ManagerOrderJPanel(userProcessContainer,useraccount,warehouseEnterprises,distribution);
        userProcessContainer.add("ManagerOrderJPanel", managerOrderJPanel);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
    }//GEN-LAST:event_btnShippingOrderActionPerformed

    private void btnDeliveryManActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeliveryManActionPerformed
        // TODO add your handling code here:
        ManagerAssignDeliveryJPanel managerAssignDeliveryJPanel = new ManagerAssignDeliveryJPanel(userProcessContainer,useraccount,warehouseEnterprises,distribution);
        userProcessContainer.add("ManagerAssignDeliveryJPanel", managerAssignDeliveryJPanel);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnDeliveryManActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        populateTable();
    }//GEN-LAST:event_btnRefreshActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeliveryMan;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnShippingOrder;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblWorkRequest;
    // End of variables declaration//GEN-END:variables
}
