/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Manager;

import Business.Distribution.Distribution;
import Business.Enterprise.Enterprise;
import Business.Order.Order;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.CustomerOrderWorkRequest;
import Business.WorkQueue.StoreAdminOrderWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author gauthamrajsimhapulipati
 */
public class ManagerAssignDeliveryJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManagerAssignDeliveryJPanel
     */
    
    private JPanel userProcessContainer;
    private UserAccount useraccount;
    private ArrayList<Enterprise> warehouseEnterprises;
    private Distribution distribution;
    
    public ManagerAssignDeliveryJPanel(JPanel userProcessContainer, UserAccount useraccount, ArrayList<Enterprise> warehouseEnterprises, Distribution distribution) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.useraccount = useraccount;
        this.warehouseEnterprises = warehouseEnterprises;
        this.distribution = distribution;
        
        populateTable();
        populateJComboBox();
        populateJComboBox2();
    }
    private void populateJComboBox2(){
        retailDeliveryManJComboBox.removeAllItems();
        
        String del = "Retail Delivery Man";
        
        for(UserAccount ua:distribution.getUserAccountDirectory().getUserAccountList()){
            if(ua.getRole().toString().equals(del)){
                retailDeliveryManJComboBox.addItem(ua);
            }
        }
    }
    
    private void populateJComboBox(){
        homeDeliveryManJComboBox.removeAllItems();
        
        String del = "Home Delivery Man";
        
        for(UserAccount ua:distribution.getUserAccountDirectory().getUserAccountList()){
            if(ua.getRole().toString().equals(del)){
                homeDeliveryManJComboBox.addItem(ua);
            }
        }
    }
    
    private void populateTable(){
        DefaultTableModel model = (DefaultTableModel)tblOrder.getModel();
        model.setRowCount(0);
        
        ArrayList<WorkRequest> wr = distribution.getWorkQueue().getWorkRequestList();
        
        for(int i=wr.size()-1; i>=0;i--){
            
            CustomerOrderWorkRequest lt = (CustomerOrderWorkRequest)wr.get(i);
            Order order = lt.getOrder();
                Object[] row = new Object[5];
                row[0] = lt;
                row[1] = order.getId();
                row[2] = order.getQuantity();
                row[3] = order.getPrice();
                row[4] = lt.getStatus();
                model.addRow(row);
        }
        ArrayList<WorkRequest> wr2 = distribution.getWorkQueue().getWorkRequestList2();
        for(int i=wr2.size()-1; i>=0;i--){
            
            StoreAdminOrderWorkRequest lt = (StoreAdminOrderWorkRequest)wr2.get(i);
            Order order = lt.getOrder();
                Object[] row = new Object[5];
                row[0] = lt;
                row[1] = order.getId();
                row[2] = order.getQuantity();
                row[3] = order.getPrice();
                row[4] = lt.getStatus();
                model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblOrder = new javax.swing.JTable();
        btnAccept = new javax.swing.JButton();
        btnReject = new javax.swing.JButton();
        homeDeliveryManJComboBox = new javax.swing.JComboBox();
        AssignShipping = new javax.swing.JButton();
        retailDeliveryManJComboBox = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        AssignRetail = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btnBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        AssignRetail1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 236, 179));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Select Home Delivery Man:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 390, -1, 27));

        tblOrder.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Message", "Order ID", "Quantity", "Price", "Order Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblOrder);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 133, 640, 175));

        btnAccept.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        btnAccept.setText("Accept");
        btnAccept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcceptActionPerformed(evt);
            }
        });
        add(btnAccept, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 133, 100, 40));

        btnReject.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        btnReject.setText("Reject");
        btnReject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRejectActionPerformed(evt);
            }
        });
        add(btnReject, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 268, 100, 40));

        homeDeliveryManJComboBox.setBackground(new java.awt.Color(153, 191, 170));
        homeDeliveryManJComboBox.setForeground(new java.awt.Color(92, 61, 70));
        homeDeliveryManJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        homeDeliveryManJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeDeliveryManJComboBoxActionPerformed(evt);
            }
        });
        add(homeDeliveryManJComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 390, 111, 30));

        AssignShipping.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        AssignShipping.setText("Assign Home Delivery Man");
        AssignShipping.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AssignShippingActionPerformed(evt);
            }
        });
        add(AssignShipping, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 450, -1, 40));

        retailDeliveryManJComboBox.setBackground(new java.awt.Color(153, 191, 170));
        retailDeliveryManJComboBox.setForeground(new java.awt.Color(92, 61, 70));
        retailDeliveryManJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        retailDeliveryManJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retailDeliveryManJComboBoxActionPerformed(evt);
            }
        });
        add(retailDeliveryManJComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 390, 105, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Select Retail Delivery Man:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 390, -1, 27));

        AssignRetail.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        AssignRetail.setText("Assign Retail Delivery Man");
        AssignRetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AssignRetailActionPerformed(evt);
            }
        });
        add(AssignRetail, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 450, -1, 40));

        jPanel1.setBackground(new java.awt.Color(203, 186, 131));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(239, 239, 239), 4));

        btnBack.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Georgia", 1, 36)); // NOI18N
        jLabel1.setText("Process Order & Assign Delivery Man");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addContainerGap(45, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, -1));

        AssignRetail1.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        AssignRetail1.setText("Refresh");
        AssignRetail1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AssignRetail1ActionPerformed(evt);
            }
        });
        add(AssignRetail1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 100, 20));
    }// </editor-fold>//GEN-END:initComponents

    private void btnAcceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcceptActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblOrder.getSelectedRow();
        if (selectedRow < 0){
            JOptionPane.showMessageDialog(this, "Please select a row to accept");
            return;
        }

        WorkRequest request = (WorkRequest) tblOrder.getValueAt(selectedRow, 0);
        if(request.getStatus().equals("Customer order placed")){
            request.setStatus("Customer Order Accepted");
        }
        else if(request.getStatus().equals("Retail Order placed")){
            request.setStatus("Retail Order Accepted");
        }
        else{
            JOptionPane.showMessageDialog(this, "Request has been previously accepted/ rejected");
        }
        populateTable();
    }//GEN-LAST:event_btnAcceptActionPerformed

    private void btnRejectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRejectActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblOrder.getSelectedRow();
        if (selectedRow < 0){
            JOptionPane.showMessageDialog(this, "Please select a row to reject the order");
            return;
        }

        WorkRequest request = (WorkRequest) tblOrder.getValueAt(selectedRow, 0);
        if(request.getStatus().equals("Sent")){
            request.setStatus("Rejected");
        }
        else{
            JOptionPane.showMessageDialog(this, "Request has been previously accepted/ rejected");
        }
        populateTable();
    }//GEN-LAST:event_btnRejectActionPerformed

    private void homeDeliveryManJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeDeliveryManJComboBoxActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_homeDeliveryManJComboBoxActionPerformed

    private void AssignShippingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AssignShippingActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblOrder.getSelectedRow();
        if (selectedRow < 0){
            JOptionPane.showMessageDialog(this, "Please select a row");
            return;
        }

        CustomerOrderWorkRequest request = (CustomerOrderWorkRequest) tblOrder.getValueAt(selectedRow, 0);
        if(request.getStatus().equals("Customer Order Accepted")){
            
            UserAccount ua1 = (UserAccount)homeDeliveryManJComboBox.getSelectedItem();
            request.setReceiver(ua1);
            request.setStatus("On the way");
            populateTable();
        }
        else{
            
                JOptionPane.showMessageDialog(this, "");
            
        }
    }//GEN-LAST:event_AssignShippingActionPerformed

    private void retailDeliveryManJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retailDeliveryManJComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_retailDeliveryManJComboBoxActionPerformed

    private void AssignRetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AssignRetailActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblOrder.getSelectedRow();
        if (selectedRow < 0){
            JOptionPane.showMessageDialog(this, "Please select a row");
            return;
        }

        StoreAdminOrderWorkRequest request = (StoreAdminOrderWorkRequest) tblOrder.getValueAt(selectedRow, 0);
        if(request.getStatus().equals("Retail Order Accepted")){
            
            UserAccount ua1 = (UserAccount)retailDeliveryManJComboBox.getSelectedItem();
            request.setReceiver(ua1);
            request.setStatus("On the way");
            populateTable();
        }
        else{
            
                JOptionPane.showMessageDialog(this, "Please accept the order");
            
        }
    }//GEN-LAST:event_AssignRetailActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        ManagerWorkJPanel hentadjp = (ManagerWorkJPanel) component;
        //sysAdminwjp.populateTree();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void AssignRetail1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AssignRetail1ActionPerformed
        // TODO add your handling code here:
        populateTable();
    }//GEN-LAST:event_AssignRetail1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AssignRetail;
    private javax.swing.JButton AssignRetail1;
    private javax.swing.JButton AssignShipping;
    private javax.swing.JButton btnAccept;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnReject;
    private javax.swing.JComboBox homeDeliveryManJComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox retailDeliveryManJComboBox;
    private javax.swing.JTable tblOrder;
    // End of variables declaration//GEN-END:variables
}
