/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Technician;

import Business.Hospital.Hospital;
import Business.Products.Product;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.TestRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import userinterface.ApproveDoctor.ApproveDoctorJPanel;

/**
 *
 * @author gauthamrajsimhapulipati
 */
public class TechnicianJPanel extends javax.swing.JPanel {

    /**
     * Creates new form TechnicianJPanel
     */
    
    private JPanel userProcessContainer;
    private UserAccount account;
    private Hospital hospital;
    
    public TechnicianJPanel(JPanel userProcessContainer, UserAccount account, Hospital hospital) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.hospital = hospital;
        populateTable();
        populateDoctorJComboBox();
    }
    
    private void populateDoctorJComboBox(){
        doctorJComboBox.removeAllItems();
        
        String del = "Approve Doctor";
        
        for(UserAccount ua:hospital.getUserAccountDirectory().getUserAccountList()){
            if(ua.getRole().toString().equals(del)){
                doctorJComboBox.addItem(ua);
            }
        }
    }
    
    private void populateTable(){
        DefaultTableModel model = (DefaultTableModel)tblRequests.getModel();
        model.setRowCount(0);
        
        ArrayList<WorkRequest> wr = hospital.getWorkQueue().getWorkRequestList2();
        for(int i=wr.size()-1; i>=0;i--){
            
            TestRequest lt = (TestRequest)wr.get(i);
            Product product = lt.getProduct();
                Object[] row = new Object[5];
                row[0] = lt;
                row[1] = product.getProductName();
                row[2] = lt.getCustomer().getEmployee().getName();
                row[3] = lt.getStatus();
                String result = lt.getTestResult();
                row[4]  = result == null ? "Waiting" : result;
                model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblRequests = new javax.swing.JTable();
        btnPerformTest = new javax.swing.JButton();
        btnSendResults = new javax.swing.JButton();
        doctorJComboBox = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnPerformTest1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(197, 222, 221));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblRequests.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Message", "Test kit", "Customer Name", "Status", "Result"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblRequests);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 215, 514, 202));

        btnPerformTest.setBackground(new java.awt.Color(40, 75, 99));
        btnPerformTest.setFont(new java.awt.Font("Devanagari MT", 1, 14)); // NOI18N
        btnPerformTest.setForeground(new java.awt.Color(255, 255, 255));
        btnPerformTest.setText("Perform Test");
        btnPerformTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPerformTestActionPerformed(evt);
            }
        });
        add(btnPerformTest, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 310, -1, 55));

        btnSendResults.setBackground(new java.awt.Color(40, 75, 99));
        btnSendResults.setFont(new java.awt.Font("Devanagari MT", 1, 14)); // NOI18N
        btnSendResults.setForeground(new java.awt.Color(255, 255, 255));
        btnSendResults.setText("Send Result to Doctor");
        btnSendResults.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendResultsActionPerformed(evt);
            }
        });
        add(btnSendResults, new org.netbeans.lib.awtextra.AbsoluteConstraints(462, 455, 154, 42));

        doctorJComboBox.setBackground(new java.awt.Color(153, 191, 170));
        doctorJComboBox.setForeground(new java.awt.Color(92, 61, 70));
        doctorJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        doctorJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doctorJComboBoxActionPerformed(evt);
            }
        });
        add(doctorJComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 461, 184, 30));

        jLabel1.setFont(new java.awt.Font("Devanagari MT", 1, 14)); // NOI18N
        jLabel1.setText("Select Doctor");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 467, 97, -1));

        jPanel1.setBackground(new java.awt.Color(40, 75, 99));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 204), 3, true));

        jLabel2.setFont(new java.awt.Font("Devanagari MT", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Technician Process (Test)");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 726, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel2)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 742, -1));

        btnPerformTest1.setBackground(new java.awt.Color(40, 75, 99));
        btnPerformTest1.setFont(new java.awt.Font("Devanagari MT", 1, 14)); // NOI18N
        btnPerformTest1.setForeground(new java.awt.Color(255, 255, 255));
        btnPerformTest1.setText("Refresh");
        btnPerformTest1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPerformTest1ActionPerformed(evt);
            }
        });
        add(btnPerformTest1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 430, -1, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void btnPerformTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPerformTestActionPerformed
        // TODO add your handling code here:
        
        int selectedRow = tblRequests.getSelectedRow();
        
        if (selectedRow < 0){
            JOptionPane.showMessageDialog(this, "Please select a row to process this order");
            return;
        }
        
        TestRequest request = (TestRequest)tblRequests.getValueAt(selectedRow, 0);
        
        if(!request.getStatus().equals("Sent for testing")){
            if(request.getStatus().equals("Processing")){
                
            }
            else{
                JOptionPane.showMessageDialog(this, "This test has been processed before");
                return;
            }
            
        }
     
        request.setStatus("Processing");
        
        PerformTestJPanel performTestJPanel = new PerformTestJPanel(userProcessContainer,request);
        userProcessContainer.add("PerformTestJPanel", performTestJPanel);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnPerformTestActionPerformed

    private void btnSendResultsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendResultsActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblRequests.getSelectedRow();
        if (selectedRow < 0){
            JOptionPane.showMessageDialog(this, "Please select a row");
            return;
        }

        TestRequest request = (TestRequest) tblRequests.getValueAt(selectedRow, 0);
        if(request.getStatus().equals("Test finished")){
            
            UserAccount ua1 = (UserAccount)doctorJComboBox.getSelectedItem();
            request.setReceiver(ua1);
            request.setStatus("Sent to Doctor");
            populateTable();
        }
        else{
            if(request.getStatus().equals("Sent")){
                JOptionPane.showMessageDialog(this, "Please accept this request to assign");
            }
            else{
                JOptionPane.showMessageDialog(this, "Request has been previously assigned/ rejected");
            }
        }
    }//GEN-LAST:event_btnSendResultsActionPerformed

    private void doctorJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doctorJComboBoxActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_doctorJComboBoxActionPerformed

    private void btnPerformTest1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPerformTest1ActionPerformed
        // TODO add your handling code here:
        populateTable();
    }//GEN-LAST:event_btnPerformTest1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPerformTest;
    private javax.swing.JButton btnPerformTest1;
    private javax.swing.JButton btnSendResults;
    private javax.swing.JComboBox doctorJComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblRequests;
    // End of variables declaration//GEN-END:variables
}
