/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Laboratory;

import Business.Hospital.Hospital;
import Business.Products.Product;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.TestRequest;
import Business.WorkQueue.WorkRequest;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author gauthamrajsimhapulipati
 */
public class LabAdminJPanel extends javax.swing.JPanel {

    /**
     * Creates new form LabAdminJPanel
     */
    
    private JPanel userProcessContainer;
    private UserAccount account;
    private Hospital hospital;
    
    public LabAdminJPanel(JPanel userProcessContainer, UserAccount account, Hospital hospital) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.hospital = hospital;
        populateTable();
        populateJComboBox();
    }
    
    private void populateJComboBox(){
        technicianJComboBox.removeAllItems();
        
        String del = "Technician";
        
        for(UserAccount ua:hospital.getUserAccountDirectory().getUserAccountList()){
            if(ua.getRole().toString().equals(del)){
                technicianJComboBox.addItem(ua);
            }
        }
    }
    
    private void populateTable(){
        DefaultTableModel model = (DefaultTableModel)tblTestRequest.getModel();
        model.setRowCount(0);
        
        ArrayList<WorkRequest> wr = hospital.getWorkQueue().getWorkRequestList2();
        for(int i=wr.size()-1; i>=0;i--){
            
            TestRequest lt = (TestRequest)wr.get(i);
            if(lt.getCustomer()==null){
                continue;
            }
            Product product = lt.getProduct();
                Object[] row = new Object[4];
                row[0] = lt;
                row[1] = product.getProductName();
                row[2] = lt.getCustomer().getEmployee().getName();
                row[3] = lt.getStatus();
                model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblTestRequest = new javax.swing.JTable();
        btnExamine = new javax.swing.JButton();
        btnReject = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnAssign = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        technicianJComboBox = new javax.swing.JComboBox();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 241, 230));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblTestRequest.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Message", "Test Kit", "Customer Name", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblTestRequest);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 196, 470, 164));

        btnExamine.setBackground(new java.awt.Color(153, 255, 153));
        btnExamine.setFont(new java.awt.Font("Devanagari MT", 1, 14)); // NOI18N
        btnExamine.setText("Examine");
        btnExamine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExamineActionPerformed(evt);
            }
        });
        add(btnExamine, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 250, -1, 46));

        btnReject.setBackground(new java.awt.Color(255, 102, 102));
        btnReject.setFont(new java.awt.Font("Devanagari MT", 1, 14)); // NOI18N
        btnReject.setText("Reject");
        btnReject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRejectActionPerformed(evt);
            }
        });
        add(btnReject, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 314, 97, 46));

        jLabel1.setFont(new java.awt.Font("Devanagari MT", 1, 14)); // NOI18N
        jLabel1.setText("Select Lab Technician : ");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 384, -1, -1));

        btnAssign.setBackground(new java.awt.Color(203, 153, 126));
        btnAssign.setFont(new java.awt.Font("Devanagari MT", 1, 14)); // NOI18N
        btnAssign.setText("Assign");
        btnAssign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignActionPerformed(evt);
            }
        });
        add(btnAssign, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 378, -1, -1));

        jLabel2.setText("Test Sample :");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 216, -1, -1));

        technicianJComboBox.setBackground(new java.awt.Color(153, 191, 170));
        technicianJComboBox.setForeground(new java.awt.Color(92, 61, 70));
        technicianJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        technicianJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                technicianJComboBoxActionPerformed(evt);
            }
        });
        add(technicianJComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(267, 378, 187, 30));

        jPanel1.setBackground(new java.awt.Color(203, 153, 126));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 51, 0), 3, true));

        jLabel3.setFont(new java.awt.Font("Devanagari MT", 1, 36)); // NOI18N
        jLabel3.setText("Manage Laboratory Tests");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(149, 149, 149)
                .addComponent(jLabel3)
                .addContainerGap(193, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(50, 50, 50))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 752, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnExamineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExamineActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblTestRequest.getSelectedRow();
        if (selectedRow < 0){
            JOptionPane.showMessageDialog(this, "Please select a row to examine");
            return;
        }

        WorkRequest request = (WorkRequest) tblTestRequest.getValueAt(selectedRow, 0);
        if(request.getStatus().equals("Sample sent")){
            request.setStatus("Accepted");
        }
        else{
            JOptionPane.showMessageDialog(this, "Request has been previously accepted/ rejected");
        }
        populateTable();
    }//GEN-LAST:event_btnExamineActionPerformed

    private void technicianJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_technicianJComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_technicianJComboBoxActionPerformed

    private void btnRejectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRejectActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblTestRequest.getSelectedRow();
        if (selectedRow < 0){
            JOptionPane.showMessageDialog(this, "Please select a row to reject sample");
            return;
        }

        WorkRequest request = (WorkRequest) tblTestRequest.getValueAt(selectedRow, 0);
        if(request.getStatus().equals("Sent")){
            request.setStatus("Rejected");
        }
        else{
            JOptionPane.showMessageDialog(this, "Request has been previously accepted/ rejected");
        }
        populateTable();
    }//GEN-LAST:event_btnRejectActionPerformed

    private void btnAssignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblTestRequest.getSelectedRow();
        if (selectedRow < 0){
            JOptionPane.showMessageDialog(this, "Please select a row");
            return;
        }

        TestRequest request = (TestRequest) tblTestRequest.getValueAt(selectedRow, 0);
        if(request.getStatus().equals("Accepted")){
            
            UserAccount ua1 = (UserAccount)technicianJComboBox.getSelectedItem();
            request.setReceiver(ua1);
            request.setStatus("Sent for testing");
            populateTable();
        }
        else{
            if(request.getStatus().equals("Sent")){
                JOptionPane.showMessageDialog(this, "Please accept this request to assign");
            }
            else{
                JOptionPane.showMessageDialog(this, "Request has been previously assigned/ rejected");
            }
        }
    }//GEN-LAST:event_btnAssignActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAssign;
    private javax.swing.JButton btnExamine;
    private javax.swing.JButton btnReject;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblTestRequest;
    private javax.swing.JComboBox technicianJComboBox;
    // End of variables declaration//GEN-END:variables
}
